import type { ModelProvider } from '../types/model';

export const DEFAULT_PROVIDERS: ModelProvider[] = [
  {
    id: 'gemini',
    name: 'Google Gemini',
    type: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    apiKey: '',
    isEnabled: true,
    isOfficial: true,
    models: [
      {
        id: 'gemini-2.5-flash',
        name: 'Gemini 2.5 Flash',
        providerId: 'gemini',
        description: 'Google 新一代超快速多模态模型',
        supportsReasoning: false,
        contextWindow: 1000000,
      },
      {
        id: 'gemini-2.5-pro',
        name: 'Gemini 2.5 Pro',
        providerId: 'gemini',
        description: 'Google 强力复杂逻辑推理与 Coding 旗舰模型',
        supportsReasoning: true,
        contextWindow: 2000000,
      },
      {
        id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        providerId: 'gemini',
        description: '轻量轻快高性价比多模态模型',
        supportsReasoning: false,
        contextWindow: 1000000,
      },
      {
        id: 'gemini-3.6-flash',
        name: 'Gemini 3.6 Flash (High)',
        providerId: 'gemini',
        description: '高级智能加速模型',
        supportsReasoning: true,
        contextWindow: 1000000,
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    type: 'deepseek',
    baseUrl: 'https://api.deepseek.com/v1',
    apiKey: '',
    isEnabled: true,
    isOfficial: true,
    models: [
      {
        id: 'deepseek-chat',
        name: 'DeepSeek V3 (Chat)',
        providerId: 'deepseek',
        description: '通用高性价比大语言模型',
        supportsReasoning: false,
        contextWindow: 64000,
      },
      {
        id: 'deepseek-reasoner',
        name: 'DeepSeek R1 (Reasoner)',
        providerId: 'deepseek',
        description: '逻辑推理强化模型，输出深度思考 Chain-of-Thought',
        supportsReasoning: true,
        contextWindow: 64000,
      },
      {
        id: 'deepseek-coder',
        name: 'DeepSeek Coder',
        providerId: 'deepseek',
        description: '专业代码生成与重构模型',
        supportsReasoning: false,
        contextWindow: 64000,
      },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    type: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    apiKey: '',
    isEnabled: true,
    isOfficial: true,
    models: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        providerId: 'openai',
        description: '旗舰级多模态模型',
        supportsReasoning: false,
        contextWindow: 128000,
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        providerId: 'openai',
        description: '轻量高效全能模型',
        supportsReasoning: false,
        contextWindow: 128000,
      },
      {
        id: 'o3-mini',
        name: 'o3-mini (Reasoning)',
        providerId: 'openai',
        description: '强逻辑推理模型',
        supportsReasoning: true,
        contextWindow: 200000,
      },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama (Local)',
    type: 'ollama',
    baseUrl: 'http://localhost:11434/v1',
    apiKey: 'ollama',
    isEnabled: true,
    isOfficial: false,
    models: [
      {
        id: 'deepseek-r1:14b',
        name: 'DeepSeek R1 14B (Local)',
        providerId: 'ollama',
        description: '本地运行的 14B 推理模型',
        supportsReasoning: true,
      },
      {
        id: 'llama3.3:70b',
        name: 'Llama 3.3 70B (Local)',
        providerId: 'ollama',
        description: '本地极强通用大模型',
        supportsReasoning: false,
      },
      {
        id: 'qwen2.5-coder:32b',
        name: 'Qwen 2.5 Coder 32B',
        providerId: 'ollama',
        description: '本地代码生成专家模型',
        supportsReasoning: false,
      },
    ],
  },
  {
    id: 'qwen',
    name: '通义千问 (Qwen)',
    type: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiKey: '',
    isEnabled: true,
    isOfficial: true,
    models: [
      {
        id: 'qwen-max',
        name: 'Qwen Max',
        providerId: 'qwen',
        description: '阿里云通义千问超大规模模型',
      },
      {
        id: 'qwen-plus',
        name: 'Qwen Plus',
        providerId: 'qwen',
        description: '平衡性能与效率模型',
      },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    type: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    apiKey: '',
    isEnabled: true,
    isOfficial: true,
    models: [
      {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        providerId: 'anthropic',
        description: '最强 Coding 与逻辑分析模型',
        supportsReasoning: true,
      },
    ],
  },
];
